<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\Application\\Settings\\SettingsInterface' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static function () {
            return new \App\Application\Settings\Settings([
                'displayErrorDetails' => true, // Should be set to false in production
                'logError' => false,
                'logErrorDetails' => false,
                'addContentLengthHeader' => false, // Allow the web server to send the content-length header
                'renderer' => [
                    'template_path' => '/Users/fgx/Projects/Me/bartab/src' . '/../templates/',
                ],
                'view' => [
                    'template_path' => '/Users/fgx/Projects/Me/bartab/src' . '/../templates',
                    'twig' => [
                        'cache' => '/Users/fgx/Projects/Me/bartab/src' . '/../cache/twig',
                        'debug' => true,
                        'auto_reload' => true,
                    ],
                ],
                'logger' => [
                    'name' => 'slim-app',
                    'path' => isset($_ENV['docker']) ? 'php://stdout' : '/Users/fgx/Projects/Me/bartab/src' . '/../logs/app.log',
                    'level' => \Monolog\Logger::DEBUG,
                ],
            ]);
        }, 'App\\Application\\Settings\\SettingsInterface');
    }

}
